Implement PLOOKup gate
dusk-network/plonk pull request #330
Opened 2020-11-27 00:28 UTC by Bounce23

This PR will focus on the standard composer, and will implement the lookup gate for construction in zk proofs.

2020-12-22 16:57 UTC, Bounce23 commented
This PR is ready for review. It the base for PR #334, thus perhaps it is better to have that merged in first.

2020-12-23 10:13 UTC, ZER0 requested changes
Some changes need to be done before proceed, see the comments.

2020-12-23 12:09 UTC, Bounce23 commented on plookup/src/table/lookup_table.rs
> +                .for_each(|row| {
This function has to push each row and I tried to `collect` but for some reason the trait isn't implemented and I can't figure away to do it with the iterator.

2020-12-23 12:10 UTC, Bounce23 commented on plookup/src/multiset.rs
> +    pub fn sort_and_index(&self, f: &MultiSet) -> Result<MultiSet, PlookupErrors> {
Name change done

2020-12-23 12:10 UTC, Bounce23 commented on plookup/src/multiset.rs
> +        let length = self.0.len();
It cannot, this is added in the doc comments

2020-12-23 12:10 UTC, Bounce23 commented on plookup/src/multiset.rs
> +    pub fn is_subset_of(&self, other: &MultiSet) -> bool {
Amended

2020-12-23 12:10 UTC, Bounce23 commented on plookup/src/multiset.rs
> +        let _s: Vec<BlsScalar> = Vec::with_capacity(self.0.len() + f.0.len());
Amended

2020-12-23 12:10 UTC, Bounce23 commented on plookup/src/multiset.rs
> +    fn from_slice(slice: &[BlsScalar]) -> MultiSet {
Done

2020-12-23 12:10 UTC, Bounce23 commented on plookup/src/table/witness_table.rs
> +    pub fn new() -> Self {
Done

2020-12-23 12:11 UTC, Bounce23 commented on plookup/src/table/witness_table.rs
> +    pub fn new() -> Self {
Done

2020-12-23 12:12 UTC, Bounce23 commented on plookup/src/multiset.rs
> +        assert!(n.is_power_of_two());
It is not for debugging, so not to use an `assert!` in normal code, we could have a result returned, or leave it as it is?

2020-12-23 12:12 UTC, Bounce23 commented on plookup/src/table/lookup_table.rs
> +    pub fn new() -> Self {
Done

2020-12-23 12:12 UTC, Bounce23 commented on plookup/src/multiset.rs
> +    pub fn len(&self) -> usize {
Done

2020-12-23 12:12 UTC, Bounce23 commented on plookup/src/multiset.rs
> +            if is_subset == false {
Done with a `contains all`

2020-12-23 12:12 UTC, Bounce23 commented on plookup/src/multiset.rs
> +    pub fn new() -> MultiSet {
Done

2020-12-23 12:12 UTC, Bounce23 commented on plookup/Cargo.toml
> +canon = ["dusk-bls12_381/canon", "dusk-jubjub/canon", "canonical"]
Removed

2020-12-23 12:12 UTC, Bounce23 commented on plookup/Cargo.toml
> +rand = "0.7.0"
Amended

2020-12-23 12:12 UTC, Bounce23 commented on plookup/Cargo.toml
> +canonical = {version = "0.4", optional = true}
Amended

2020-12-23 12:13 UTC, Bounce23 commented on plookup/Cargo.toml
> +authors = ["Luke Pearson <luke@dusk.network>"]
He has now been added

2020-12-23 12:13 UTC, Bounce23 commented on .gitignore
> +.idea/
Amended and this is now ignored only in the main `cargo.toml`

2020-12-23 12:13 UTC, Bounce23 commented on plookup/.gitignore
> +.idea/
As below

2021-02-05 15:24 UTC, CPerezz commented
If this PR is going to be merged, commits like 2742337 shouldn't exist at all. Make sure to rebase and clean this branch as much as possible by removing all of the non-meaningful commits

2021-02-05 15:26 UTC, ZER0 commented
As discussed with @Bounce23, this PR is not longer valid and is going to be closed as wontfix.

2021-02-05 15:26 UTC, closed without merging