Implementation of multivariate hash function
dusk-network/plonk pull request #334
Opened 2020-12-12 13:59 UTC by EDGDrummond

Build the logic for the hash table to be used for future. Some details still need to be worked out.

In this PR we are going to be implementing a bitwise hash function tailored to our plookup gates. This allows us to interoperate plonk between different hash function (those native and non native to our finite field). 

This issue lies within #325.

2020-12-18 09:51 UTC, CPerezz requested changes
Half of the code is commented out. And also, there are no tests at all. So this is not in a status on which we can consider it mergeable.

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +        // println!("f_rows: {:?}", f_rows);
ditto.

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +            // println!("i: {}", i);
Prints shouldn't be here.

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +            // println!("eval: {}", eval);
ditto

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +            // }
Why is this commented out?

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +                // }
ditto

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +// }
Why is this all commented out? Either remove it or use it.

2020-12-18 09:51 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +}
This is not testing anything.

2020-12-18 09:52 UTC, CPerezz commented on plookup/src/table/hash_tables/constants.rs
> +// const p: usize = 52435875175126190479447740508185965837690552500527637822603658699938581184513;
Use BlsScalar (if applies). But I'm not sure if it will fit.

2020-12-18 17:02 UTC, Bounce23 commented
There was an issue, as discussed on a call with Carlos and I. It is assumed that an incorrect use of git merge had polluted the history and caused `outdated` files to appear on the PR. This is now fixed.

2020-12-23 10:01 UTC, CPerezz commented
The merge conflicts should be resolved before merging.

2020-12-23 10:57 UTC, ZER0 requested changes
Address the comments in #330, then you can merge it in `plookup_gate` and rebase this one.
I will proceed with the review after that, please ask a second round of review once it's done.

2020-12-29 10:54 UTC, CPerezz requested changes
Some things to think about/refactor if what I suggested makes sense to you

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/multiset.rs
> +        let mut table = WitnessTable3Arity::default();
We should use `min_const_generics` for this WitnessTable's with different arity values known beforehand.

Could you file an issue for it?

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +    pub end_rows: Vec<[BlsScalar; 4]>,
Don't we know the size of this Vec's beforehand so that we can use arrays?

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +    fn f_rows(&mut self, f: Polynomial) {
Can't you send a `&Polynomial` instead?

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +    fn f_rows(&mut self, f: Polynomial) {
Also, it is possible that this fn can be declared as `const`

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +            self.first_rows.push(row);
If you'll always push `V + 1` elements. This does not need to be a `Vec` and can be an array instead.

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +                self.middle_rows.push(row);
Same as above

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +        for _ in 1..(2i32.pow(T_S.try_into().unwrap())) {
Why do you need a `try_into`? Declare `T_S` with the type you need.

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +    fn binary_end_rows(&mut self) {
Is this fn needed? It only pushes empty rows so this could be done directly in the generation of `Self`.

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +    pub fn construct_table(f: Polynomial) -> Self {
Can't you use `&Polynomial`?

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +    }
Some of these could be arrays.. Also you already know most of the values you'll place.

2020-12-29 10:54 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +pub fn incrementer(mut row: &mut [BlsScalar; 4], i: usize) {
if `i > 4` this  will panic. Impl error handling or mention in the docs that this can panic.

2020-12-30 11:28 UTC, Bounce23 commented
Must be noted that we can't turn f_rows into a const fn because there's a for loop, and that the end_rows function doesn't push empty rows, since the incrementer makes sure the bits are flipped

2021-01-05 15:37 UTC, CPerezz requested changes
Changes requested are still not addressed.

2021-01-05 15:37 UTC, CPerezz commented on plookup/src/table/hash_tables/tables.rs
> +pub fn incrementer(mut row: &mut [BlsScalar; 4], i: usize) {
Still not addressed

2021-01-13 15:21 UTC, CPerezz approved these changes
Don't want to extend this more. Will add comments once I see the overall solution. This is good enough to prototype the rest of the solution

2021-01-22 00:06 UTC, Bounce23 commented
As per the above comments, this will be merged.

2021-01-22 00:06 UTC, merged