Replace tempfile by tempdir as dev_dep
dusk-network/plonk pull request #499
Opened 2021-04-15 11:27 UTC by CPerezz

Resolves: #493

2021-04-16 10:59 UTC, ZER0 requested changes

2021-04-16 10:59 UTC, ZER0 commented on src/circuit.rs
>          let tmp = TempDir::new("plonk-keys-test-full")
As GA said, the dirname will be autogenerated, you don't need to specify one. You can just call `let tmp = TempDir::new()`

2021-04-20 01:32 UTC, ZER0 approved these changes

2021-04-20 08:01 UTC, CPerezz commented
We can't merge that @ZER0 .

`tempfile` reilies on `rand` with features `getrandom` which requires `std`. Even this is a dev-dependency, is confusing cargo and it pulls in std into the mix.. 

We should consider even to remove this dep maybe and just create the dirs by ourseleves under `/tmp` or something similar.

2021-04-22 12:44 UTC, vlopes11 approved these changes
LGTM

2021-04-23 10:07 UTC, CPerezz commented
Closing this until we have a better solution.

2021-04-23 10:07 UTC, closed without merging