Improve crate documentation following Rust guidelies
dusk-network/plonk pull request #508
Opened 2021-04-20 17:35 UTC by CPerezz

This mainly focuses on:
- Extend the documentation of the crate exported structs,
traits & it's associated methods.
- Improve the quality of the previous existing docs.
- Add doc code examples as docs.
- Adapt the docs to the Rust documentation guidelines

Resolves: #505

2021-04-21 10:05 UTC, ZER0 requested changes
I stopped to review and test since we have either two scenarios:
1. The additional markdown for links is unnecessary and sometimes actually harmful since it points to the wrong page (therefore those addition you made can be reverted)
2. Your local distribution of `cargo doc` differs from mine when it generates such links. 

So before proceed to comment everything, let's double check in which scenario are we (for example, check the links of the types I've commented as "harmful" and see if they lead to a wrong page, and then try to remove it and check if they're working).

2021-04-21 10:05 UTC, ZER0 commented on src/circuit.rs
> +    /// [`VerifierKey`]: struct.VerifierKey.html
Not necessary.

2021-04-21 10:05 UTC, ZER0 commented on src/circuit.rs
> +    /// [`VerifierKey`]: struct.VerifierKey.html
Not necessary.

2021-04-22 12:43 UTC, vlopes11 approved these changes
LGTM

2021-04-23 09:39 UTC, ZER0 approved these changes

2021-04-23 10:02 UTC, merged