bench: Include constraints progession performance
dusk-network/plonk pull request #509
Opened 2021-04-21 16:12 UTC by vlopes11

The expected verification time of zk-Snarks is constant while the
proving time will increase depending on the number of used constraints.

This benchmark will show the performance progression without public
inputs.

Resolves #238

2021-04-21 16:28 UTC, Bounce23 requested changes
Overall it looks very good to me. One thing that may help is syntax change, perhaps its best to add in the numbers in terms of powers of two, as with the circuit padding, this format is most relatable.

2021-04-21 17:26 UTC, Bounce23 approved these changes
LGTM!

2021-04-21 18:26 UTC, CPerezz commented
Let's wait and see if #511 provides decent-enough results. If that's the case, I'll rebase it to this branch and change the Head to be this branch too. Merge here and then all together to `release-0.8`.

Is it ok @ZER0 @vlopes11 ?

2021-04-23 09:16 UTC, CPerezz approved these changes
I would like to add the new results. Afther the performance regression fixes. For the rest, LGTM.

2021-04-23 09:16 UTC, CPerezz commented on README.md
> +```
Could you run again the benches after the lates additions and add back the new results?

2021-04-23 13:36 UTC, merged