Change the reference document link
dusk-network/plonk pull request #533
Opened 2021-06-05 09:21 UTC by NoCtrlZ

Hi there!
When I click the document link, there is 404 error so I set the link about it.
But I don't know about the other bellow three documents link.
Please confirm.
Thank you!

2021-06-07 17:09 UTC, CPerezz requested changes
LGTM but the toolchain needs to be changed  to match https://github.com/dusk-network/plonk/blob/65e1a51c113603c23d3979e5367ee6832bba1bb2/rust-toolchain#L1

2021-06-07 17:09 UTC, CPerezz commented on rust-toolchain
> +nightly-2021-03-16
Please, leave the toolchain as set in `master` or in case of collision, to `nightly-06-06-2021`.

2021-06-07 17:10 UTC, CPerezz commented
Also, please add the changes under `Unreleased` section in `CHANGELOG.md`

2021-06-08 01:37 UTC, NoCtrlZ commented
Hi @CPerezz
Thank you for the review.
I fixed it according to your review.
Please confirm.
By the way, is there any developer community like discord?
I'd like to ask some questions about this implementation :sunglasses:
Thank you!

2021-06-08 01:49 UTC, NoCtrlZ commented
I added one change.
When I compiled the modules, the error happened `dusk-bytes` specific version.
so I set `dusk-bytes` module version as `0.1.4`.
```
(base) ➜  plonk git:(master) cargo test
   Compiling libc v0.2.95
   Compiling proc-macro2 v1.0.27
   Compiling autocfg v1.0.1
   Compiling unicode-xid v0.2.2
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.72
   Compiling crossbeam-utils v0.8.5
   Compiling lazy_static v1.4.0
   Compiling crossbeam-epoch v0.9.5
   Compiling rayon-core v1.9.1
   Compiling scopeguard v1.1.0
   Compiling either v1.6.1
   Compiling byteorder v1.4.3
   Compiling subtle v2.4.0
   Compiling ahash v0.4.7
   Compiling keccak v0.1.0
   Compiling remove_dir_all v0.5.3
   Compiling itertools v0.9.0
   Compiling hashbrown v0.9.1
   Compiling memoffset v0.6.4
   Compiling rayon v1.5.1
   Compiling crossbeam-channel v0.5.1
   Compiling getrandom v0.2.3
   Compiling num_cpus v1.13.0
   Compiling rand v0.4.6
   Compiling rand_core v0.6.2
   Compiling quote v1.0.9
   Compiling crossbeam-deque v0.8.0
   Compiling tempdir v0.3.7
   Compiling synstructure v0.12.4
   Compiling derive-hex v0.1.1
   Compiling zeroize_derive v1.1.0
   Compiling dusk-bytes v0.1.3
   Compiling zeroize v1.3.0
error[E0557]: feature has been removed
 --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/dusk-bytes-0.1.3/src/lib.rs:7:12
  |
7 | #![feature(external_doc)]
  |            ^^^^^^^^^^^^ feature has been removed
  |
  = note: use #[doc = include_str!("filename")] instead, which handles macro invocations

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
error: could not compile `dusk-bytes`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

2021-06-09 17:31 UTC, CPerezz commented
Hi, all seems nice. I'd maybe ask for an edit of the commit message of e38fe5c to something like: `Update CHANGELOG.md`. Which follows the same format as the others.

For the rest, looks fine!


> By the way, is there any developer community like discord?
> I'd like to ask some questions about this implementation sunglasses
> Thank you!

You can use [Github Discussions](https://github.com/dusk-network/plonk/discussions)!! We don't have any other places that I'm aware.

2021-06-09 17:32 UTC, CPerezz approved these changes
LGTM

Please, address:
> Hi, all seems nice. I'd maybe ask for an edit of the commit message of e38fe5c to something like: Update CHANGELOG.md. Which follows the same format as the others.


Once addressed, this can be merged!!
Thanks for your contribution! :smile:

2021-06-10 01:28 UTC, NoCtrlZ commented
Hi @CPerezz 
Thank you for the review!
I changed the commit message according to your review.
Please confirm!

2021-06-16 16:27 UTC, merged